export const ROLES = ["user", "manager", "admin"];
export const GENDERS = ["male", "female"];
 export const navLinks = [
    { label: "Home", to: "/" },
    { label: "About", to: "/about" },
  ];

  export const dummyUsers = [
  {
    id: 1,
    name: "Admin  User",
    email: "admin@gmail.com",
    password: "admin",
    gender: "male",
    isAdmin: true,
    role: "admin",
    bio: "Loves coding",
    dob: "1998-01-01",
    image: "https://placehold.co/50"
  },
  {
    id: 2,
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "user",
    bio: "UI/UX designer",
    dob: "1999-03-15",
    image: "https://placehold.co/50"
  },
  {
    id: 3,
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "manager",
    bio: "Handles operations",
    dob: "1995-06-25",
    image: "https://placehold.co/50"
  },
  {
    id: 4,
    name: "Sneha Mehta",
    email: "sneha.mehta@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "admin",
    bio: "Team lead",
    dob: "1997-09-10",
    image: "https://placehold.co/50"
  },
  {
    id: 5,
    name: "Amit Singh",
    email: "amit.singh@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "user",
    bio: "Frontend developer",
    dob: "2000-11-20",
    image: "https://placehold.co/50"
  },
  {
    id: 6,
    name: "Riya Kapoor",
    email: "riya.kapoor@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "user",
    bio: "Loves art",
    dob: "1996-02-14",
    image: "https://placehold.co/50"
  },
  {
    id: 7,
    name: "Karan Malhotra",
    email: "karan.m@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "developer",
    bio: "Full-stack dev",
    dob: "1994-04-12",
    image: "https://placehold.co/50"
  },
  {
    id: 8,
    name: "Neha Sinha",
    email: "neha.sinha@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "manager",
    bio: "Product owner",
    dob: "1993-08-08",
    image: "https://placehold.co/50"
  },
  {
    id: 9,
    name: "Vikram Jain",
    email: "vikram.jain@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "tester",
    bio: "QA Engineer",
    dob: "1991-12-30",
    image: "https://placehold.co/50"
  },
  {
    id: 10,
    name: "Aishwarya Nair",
    email: "aishwarya.nair@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "designer",
    bio: "Creative designer",
    dob: "1990-06-05",
    image: "https://placehold.co/50"
  },
  {
    id: 11,
    name: "Rohan Bhatt",
    email: "rohan.bhatt@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "intern",
    bio: "Learning React",
    dob: "2002-07-19",
    image: "https://placehold.co/50"
  },
  {
    id: 12,
    name: "Divya Das",
    email: "divya.das@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "admin",
    bio: "HR Manager",
    dob: "1989-11-23",
    image: "https://placehold.co/50"
  },
  {
    id: 13,
    name: "Arjun Mishra",
    email: "arjun.m@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "user",
    bio: "Backend developer",
    dob: "1997-03-02",
    image: "https://placehold.co/50"
  },
  {
    id: 14,
    name: "Tanvi Rao",
    email: "tanvi.rao@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "user",
    bio: "Scrum master",
    dob: "1996-10-11",
    image: "https://placehold.co/50"
  },
  {
    id: 15,
    name: "Mohit Arora",
    email: "mohit.arora@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "developer",
    bio: "JS enthusiast",
    dob: "1998-12-01",
    image: "https://placehold.co/50"
  },
  {
    id: 16,
    name: "Sakshi Agarwal",
    email: "sakshi.agarwal@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "admin",
    bio: "Team coordinator",
    dob: "1992-05-06",
    image: "https://placehold.co/50"
  },
  {
    id: 17,
    name: "Yash Chauhan",
    email: "yash.chauhan@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "user",
    bio: "Junior dev",
    dob: "2001-01-15",
    image: "https://placehold.co/50"
  },
  {
    id: 18,
    name: "Ishita Roy",
    email: "ishita.roy@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "designer",
    bio: "Figma expert",
    dob: "1993-09-29",
    image: "https://placehold.co/50"
  },
  {
    id: 19,
    name: "Nikhil Tiwari",
    email: "nikhil.tiwari@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "developer",
    bio: "Node.js specialist",
    dob: "1990-02-18",
    image: "https://placehold.co/50"
  },
  {
    id: 20,
    name: "Megha Bansal",
    email: "megha.bansal@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "support",
    bio: "Support lead",
    dob: "1995-06-20",
    image: "https://placehold.co/50"
  },
  {
    id: 21,
    name: "Deepak Joshi",
    email: "deepak.joshi@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "tester",
    bio: "Automation QA",
    dob: "1994-03-12",
    image: "https://placehold.co/50"
  },
  {
    id: 22,
    name: "Simran Kaur",
    email: "simran.kaur@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "admin",
    bio: "Creative lead",
    dob: "1992-08-08",
    image: "https://placehold.co/50"
  },
  {
    id: 23,
    name: "Harsh Patel",
    email: "harsh.patel@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "manager",
    bio: "Delivery manager",
    dob: "1988-07-21",
    image: "https://placehold.co/50"
  },
  {
    id: 24,
    name: "Anjali Saxena",
    email: "anjali.saxena@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "intern",
    bio: "Learning backend",
    dob: "2003-04-30",
    image: "https://placehold.co/50"
  },
  {
    id: 25,
    name: "Rakesh Yadav",
    email: "rakesh.yadav@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "support",
    bio: "Customer support",
    dob: "1990-01-19",
    image: "https://placehold.co/50"
  },
  {
    id: 26,
    name: "Preeti Desai",
    email: "preeti.desai@example.com",
    password: "password123",
    gender: "female",
    isAdmin: true,
    role: "admin",
    bio: "Company director",
    dob: "1985-11-11",
    image: "https://placehold.co/50"
  },
  {
    id: 27,
    name: "Manish Rathi",
    email: "manish.rathi@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "developer",
    bio: "React Native dev",
    dob: "1993-03-03",
    image: "https://placehold.co/50"
  },
  {
    id: 28,
    name: "Shruti Vyas",
    email: "shruti.vyas@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "HR",
    bio: "Recruiter",
    dob: "1996-06-06",
    image: "https://placehold.co/50"
  },
  {
    id: 29,
    name: "Siddharth Dubey",
    email: "siddharth.d@example.com",
    password: "password123",
    gender: "male",
    isAdmin: false,
    role: "user",
    bio: "Support trainee",
    dob: "2002-12-24",
    image: "https://placehold.co/50"
  },
  {
    id: 30,
    name: "Kritika Joshi",
    email: "kritika.joshi@example.com",
    password: "password123",
    gender: "female",
    isAdmin: false,
    role: "designer",
    bio: "UX enthusiast",
    dob: "1994-09-01",
    image: "https://placehold.co/50"
  }
];